services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - type: volume
        source: db-data 
        target: /var/lib/postgresql/data
volumes:
  db-data: